### ISSUE TITLE
Current url has no mapping

### ISSUE THREAD

**Issue by 836438020** [oatpp/oatpp-starter#1]
Current url has no mapping?
How to fix it?

**Comment by lganzzzo** [comment]
Hello @836438020 ,

can you please provide more details:
- Your endpoint declaration?
- which URL you are trying to access ?
- what OS you are running at?

Thank you,
Leonid

**Comment by lganzzzo** [comment]
@836438020 
If you are using starter-project as-is, then by going to [http://localhost:8000/](http://localhost:8000/) in the browser you should get :
```
{"statusCode": 200, "message": "Hello World!"}
```

**Comment by 836438020** [comment]
I know this project cannot support window!!!
So I git clone a example demo as "get start",
root path cannot access, tips:'404 not found!',
but other path as '/demo/api/users' allow access!
response as '[]'

**Comment by 836438020** [comment]
I use the post method has a question!
Missing valid body parameter 'userDto',
Param list:
id:1,
first-name:'xxx',
last-name:'xxxx'
-----------------------
could you help me or write an example argument?

**Comment by 836438020** [comment]
I cannot find the database config file!
As database host,user,pwd,table etc...
It can support mysql database?

**Comment by lganzzzo** [comment]
Ok, I see.

So you are using [CRUD](https://github.com/oatpp/oatpp-examples/tree/master/crud) project from examples.

For each URL you are trying to access you should define an ```ENDPOINT``` with corresponding path and method.

CRUD example project has no root mapping ```"/"``` so you have to define this endpoint by yourself.

**Please  note that you have created issue in the non-relevant repository.**

This issue will be closed.
**Please create issue for the relevant repository.**
