### ISSUE TITLE
Ubuntu utility installation

### ISSUE THREAD

**Issue by brunomerod** [oatpp/oatpp-starter#10]
## Problem using the install utility.

**CMake Error at src/cmake_install.cmake**

### Permission problems for:
> /usr/local/lib/oatpp-1.1.0
> /usr/local/include/oatpp-1.1.0
> /usr/local/lib/cmake/oatpp-1.1.0

### Solution
> sudo mkdir [folders]
> sudo chmod 777 [folders]

### Suggestion
Maybe all the modules could be installed on specific oatpp config folder, such as
> /home/[user]/.oatpp/lib
> /home/[user]/.oatpp/include
etc...

**Comment by lganzzzo** [comment]
Hello @brunomerod ,

You can also try to use cmake's `-DCMAKE_INSTALL_PREFIX` option.

Install oatpp:

```bash
cmake -DCMAKE_INSTALL_PREFIX=/my/custom/path ..
make install
```

Regards,
Leonid

**Comment by brunomerod** [comment]
Thank you very much, Leonid. I'm new to this C/C++. 

Regards,
Bruno
