### ISSUE TITLE
Need to update to 1.2?

### ISSUE THREAD

**Issue by abiank** [oatpp/oatpp-starter#12]
utility/install-oatpp-modules.sh now downloads vers 0.1.2 but cmake is looking for 0.1.1 and build can't proceeed

**Comment by lganzzzo** [comment]
Hey @abiank ,

The `utility/install-oatpp-modules.sh` script downloads the latest version from the master which is `1.2.0` currently.
Also, `CMakeLists.txt` is also requires oatpp version `1.2.0` - https://github.com/oatpp/oatpp-starter/blob/master/CMakeLists.txt#L18

So everything should be consistent.

Please also note that `utility/install-oatpp-modules.sh` is just for the reference. It's recommended to clone and install oatpp manually.

Regards,
Leonid

**Comment by abiank** [comment]
Thank You! it was just a heads up
