### ISSUE TITLE
How to post a record!

### ISSUE THREAD

**Issue by 836438020** [oatpp/oatpp-starter#2]
Body raw as 
"{"id":1,"firstName":"xxx","lastName":"xxx"}"
response as 
code=400
message=Missing valid body parameter 'userDto'

**Comment by lganzzzo** [comment]
@836438020 

**This question relates to [https://github.com/oatpp/oatpp-examples](https://github.com/oatpp/oatpp-examples) repository. Project CRUD.**

correct curl is:
```
$ curl -X POST "http://localhost:8000/demo/api/users" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"first-name\":\"string\",\"last-name\":\"string\",\"friends\":[\"string\"]}"
```

Please note that CRUD example project has swagger-ui. Please use swagger-ui to build correct requests.

swagger-ui is served at [http://localhost:8000/swagger/ui](http://localhost:8000/swagger/ui)

Again - **This question relates to [https://github.com/oatpp/oatpp-examples](https://github.com/oatpp/oatpp-examples) repository. Project CRUD.**

**Please create issues in the corresponding repositories!!!**

Regards,
Leonid
