### ISSUE TITLE
It can support mysql database?

### ISSUE THREAD

**Issue by 836438020** [oatpp/oatpp-starter#3]
I cannot find about databse config file!
as
databse host,user,pwd,port,table,etc...

**Comment by lganzzzo** [comment]
**This question relates to https://github.com/oatpp/oatpp-examples repository. Project CRUD.**

Crud project is an example project and it uses In-Memory fake Database.
To use MySql database you have to use whatever C++ MySql connector and setup MySql instance manually.

**This question relates to https://github.com/oatpp/oatpp-examples repository. Project CRUD.**

Please create issues in the corresponding repositories!!!

Regards,
Leonid
