### ISSUE TITLE
make run error

### ISSUE THREAD

**Issue by overcls** [oatpp/oatpp-starter#5]
In file included from /data/dev/cdev/oatpp-swagger-with-async-api/main/src/Logger.cpp:9:
/data/dev/cdev/oatpp-swagger-with-async-api/main/src/Logger.hpp:22:33: error: no type named 'Atom' in 'oatpp::concurrency::SpinLock'
  oatpp::concurrency::SpinLock::Atom m_atom;
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated.
make[6]: *** [CMakeFiles/example-async-api-lib.dir/src/Logger.cpp.o] Error 1
make[5]: *** [CMakeFiles/example-async-api-lib.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [main-prefix/src/main-stamp/main-build] Error 2
make[2]: *** [CMakeFiles/main.dir/all] Error 2
make[1]: *** [CMakeFiles/run.dir/rule] Error 2
make: *** [run] Error 2

**Comment by lganzzzo** [comment]
Hello @overcls ,

This issue is for repo https://github.com/lganzzzo/oatpp-swagger-with-async-api.

Fixed in https://github.com/lganzzzo/oatpp-swagger-with-async-api/commit/95fdecfec369d9d9dedb8c7340940a8127c39186

Regards,
Leonid
