### ISSUE TITLE
License

### ISSUE THREAD

**Issue by giulioroggero** [oatpp/oatpp-starter#7]
Hi @lganzzzo,
your example is really useful and I'd like to use it for a microservice template based on oat++. I checked the license on GitHub and it's stated Apache 2.0 but inside the source code of the example is stated

```c++
//
//  MyDto.hpp
//  crud
//
//  Created by Leonid on 3/13/18.
//  Copyright © 2018 oatpp. All rights reserved.
//
```

May I use this source code as starting point for my microservice template or all rights are reserved and I must start from scratch?

The new teamplate will be available here https://github.com/mia-platform-marketplace with Apache 2.0 License and the attribution of derivate work to you.

```c++
/* 
 * This project is a derivative work from oatpp-web-starter
 * Created by Leonid on 3/2/18.
 */
```

Thanks in advance for the clarification

Ciao
Giulio

**Comment by lganzzzo** [comment]
Hello @giulioroggero ,

Please use the `oatpp-starter`,- it's free to use with no restrictions.

I have to remove those headers, not to confuse users.

Best Regards,
Leonid

**Comment by giulioroggero** [comment]
Thanks @lganzzzo. I let you know when the template will be published.
Have a nice day
Giulio

**Comment by lganzzzo** [comment]
Copyright headers were removed.
